// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_category.sql

package db

import (
	"context"
)

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM public.categories WHERE id=$1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}
