// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_item.sql

package db

import (
	"context"
)

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM public.items WHERE id=$1
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}
