// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_categories_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategories = `-- name: GetCategories :many
SELECT id, user_id, name, priority FROM public.categories
WHERE user_id = $1 ORDER BY priority
`

func (q *Queries) GetCategories(ctx context.Context, userID pgtype.Int4) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByItemId = `-- name: GetCategoryByItemId :one
SELECT category_id FROM public.items
WHERE id = $1
`

func (q *Queries) GetCategoryByItemId(ctx context.Context, id int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getCategoryByItemId, id)
	var category_id pgtype.Int4
	err := row.Scan(&category_id)
	return category_id, err
}

const getCategoryByNameAndId = `-- name: GetCategoryByNameAndId :one
SELECT id, user_id, name, priority FROM public.categories
WHERE user_id = $1 AND name = $2
`

type GetCategoryByNameAndIdParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) GetCategoryByNameAndId(ctx context.Context, arg GetCategoryByNameAndIdParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameAndId, arg.UserID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Priority,
	)
	return i, err
}
