// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash FROM public.users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT ID FROM public.users
WHERE username = $1
`

func (q *Queries) GetUserId(ctx context.Context, username pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getUserId, username)
	var id int32
	err := row.Scan(&id)
	return id, err
}
