// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getItems = `-- name: GetItems :many
SELECT id, category_id, name, description, done, created_at FROM public.items WHERE category_id=$1
`

func (q *Queries) GetItems(ctx context.Context, categoryID pgtype.Int4) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
