// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: insert_item.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO public.items (category_id, name, description, done, created_at) VALUES ($1, $2, $3, false, NOW())
RETURNING id, category_id, name, description, done, created_at
`

type CreateItemParams struct {
	CategoryID  pgtype.Int4 `json:"category_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.CategoryID, arg.Name, arg.Description)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}
