// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: insert_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO public.categories (user_id, name, priority) VALUES ($1, $2, $3)
RETURNING id
`

type CreateCategoryParams struct {
	UserID   pgtype.Int4 `json:"user_id"`
	Name     pgtype.Text `json:"name"`
	Priority pgtype.Int4 `json:"priority"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Priority)
	var id int32
	err := row.Scan(&id)
	return id, err
}
