// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       int32       `json:"id"`
	UserID   pgtype.Int4 `json:"user_id"`
	Name     pgtype.Text `json:"name"`
	Priority pgtype.Int4 `json:"priority"`
}

type Item struct {
	ID          int32            `json:"id"`
	CategoryID  pgtype.Int4      `json:"category_id"`
	Name        pgtype.Text      `json:"name"`
	Description pgtype.Text      `json:"description"`
	Done        pgtype.Bool      `json:"done"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           int32       `json:"id"`
	Username     pgtype.Text `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
}
