// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sample_query.sql

package db

import (
	"context"
)

const sampleQuery = `-- name: SampleQuery :one
SELECT 'Some shit from db'
`

func (q *Queries) SampleQuery(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, sampleQuery)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
