// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_item.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateItemDoneStatus = `-- name: UpdateItemDoneStatus :one
UPDATE public.items SET done = $2
WHERE id = $1
RETURNING id, category_id, name, description, done, created_at
`

type UpdateItemDoneStatusParams struct {
	ID   int32       `json:"id"`
	Done pgtype.Bool `json:"done"`
}

func (q *Queries) UpdateItemDoneStatus(ctx context.Context, arg UpdateItemDoneStatusParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemDoneStatus, arg.ID, arg.Done)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}
